controller_list:
  - name: fake_my_robot4_controller
    type: $(arg fake_execution_type)
    joints:
      - base_to_rotator1
      - pivot1_to_arm1
      - arm1_to_pivot2
      - pivot2_to_arm2
      - arm2_to_pivot3
      - pivot3_to_arm3
initial:  # Define initial robot poses per group
  - group: my_robot4
    pose: Home